<template>
  <section id="data-policy" class="about">
    <div class="container">
      <div class="row content">
        <div class="col-12 data-policy">
          <div>
            <h1>ADX-DW Data Policy</h1>
            <ol class="list-data-policy">
              <li><i class='bx bx-arrow-from-left'></i>
                Any person or organization that would like to contribute to the Anomalous Data Exchange
                Data Warehouse (ADX-DW) must adhere to the ADX Data Policy as well as the
                <NuxtLink to="terms-and-conditions">Terms and Conditions</NuxtLink>
                of the website.
              </li>
              <li><i class='bx bx-arrow-from-left'></i>
                Data owned by private individuals and organizations is eligible for inclusion in the ADX-DW.
                Copyright of all data is retained by the individuals and organizations that have submitted the data.
              </li>
              <li><i class='bx bx-arrow-from-left'></i>
                ADX will not sell or claim ownership of any data submitted to the ADX-DW. Data may be licensed
                for commercial use through the ADX Project according to our
                <NuxtLink to="terms-and-conditions">Terms and Conditions</NuxtLink>
                and with the prior consent of the copyright holder.
              </li>
              <li><i class='bx bx-arrow-from-left'></i>
                Data held in the ADX may be removed at any time by the copyright owner.
              </li>
              <li><i class='bx bx-arrow-from-left'></i>
                No data in the ADX-DW may be used for any purpose other
                than those outlined in this policy or in the
                <NuxtLink to="terms-and-conditions">Terms and Conditions.</NuxtLink>
              </li>
            </ol>
          </div>
          <div>
            <h1>Governmental Data</h1>
            <p>ADX will not accept data for inclusion in the ADX Data Warehouse that has been originally
              generated by military or governmental agencies without the expressed written consent of said government.
              Only data released in an unclassified public manner will be considered for inclusion in the dataset.
            </p>
            <p>
              ADX does not solicit and will not publish classified or sensitive data of any government without their
              prior consent outlined in a fully executed <strong>MOU (Memorandum of Understanding)</strong>.
              Any data submitted to ADX in an unauthorized format will be deleted.
            </p>
            <p>
              Data that has been previously released by a governmental agency or prior public confirmation
              that data is of a non-classified nature will be eligible for entry in the ADX-DW.
            </p>
          </div>
          <div>
            <h1>Data Submitted by Partner Organizations</h1>
            <p>
              Organizations that partner with ADX-DW to submit data must follow predetermined <strong>Standard
              Operating Procedures (SOPs)</strong> regarding data collection and release officially
              adopted by their organization. Templates of these SOPs will be made available to partner
              organizations as part of the Memorandum of Understanding between ADX and the partner
              organizations. Data collection and transfer SOPs should be integrated into partner organizations'
              overall quality policies and training plans.
            </p>
          </div>
          <div>
            <h1>Public Open Source Data Sets</h1>
            <p>
              The ADX-DW may acquire or license entire raw data sets of air traffic, satellite, weather
              radar, or other data that may support or exclude data reported in the ADX-DW. These raw
              datasets will be publicly available for research purposes according to the
              <NuxtLink to="terms-and-conditions">Terms and Conditions.</NuxtLink>
              and according to the wishes of the copyright holder.
            </p>
          </div>
          <div>
            <h1>Data Submitted by Individuals</h1>

            ADX-DW will accept exceptional examples of data submitted by individuals on a case by case basis and at
            the discretion of the ADX administrators. Data submitted by individuals will be subject to verification of
            both provenance and authenticity. This requirements for individually data submission include:<br/><br/>

            <ul>
              <li><i class='bx bx-arrow-from-left'></i>
                Verification of the identity of the individual that holds the copyright.
              </li>
              <li><i class='bx bx-arrow-from-left'></i>
                Verification of education/professional status/demographics of observers.
              </li>
              <li><i class='bx bx-arrow-from-left'></i>
                Cognitive assessment of the observer.
              </li>
              <li><i class='bx bx-arrow-from-left'></i>
                Verification of Hearing and Eyesight of the observer.
              </li>
              <li><i class='bx bx-arrow-from-left'></i>
                At least one media file corroborating event (photo, video, flir, ect) with original
                file metadata present. Inclusion of trained observer reports may be accepted at the
                discretion of the ADX-DW administrators in lieu of corroborating media/sensor data.
              </li>
              <li><i class='bx bx-arrow-from-left'></i>
                Subject Matter Expert (SME) forensic evaluation of media regarding authenticity is required for
                inclusion into the ADX-DW, cost of this is borne by the individual submitting the observation. If
                budget and resources allow ADX may perform this verification on a case by case basis.
              </li>
            </ul>
            <p>
              * Trained Observers are individuals that can document that they have received professional
              training identifying meteorological and anthropomorphic objects in the sea, sky, or space.
            </p>
          </div>

          <div>
            <h1>Historical Data</h1>
            <p>
              Data recorded by individuals or organizations before widespread adoption of digital media may be
              included in the ADX-DW for reference use. This data will be firewalled and not included in the main
              ADX-DW dataset. Historical datasets will be considered as external datasets used for
              reference/collaboration purposes, as well as trend or aggregate analysis.
            </p>
          </div>

          <div>
            <h1>External Datasets of Historical Anomalous Observations</h1>
            <p>
              External datasets of historical observations may be mapped to the current ADX-DS format, in this case
              the programs mapping data will be made publicly available for review. These datasets will be kept
              separate from the main ADX-DW dataset, but can be merged/queried to establish trends.
            </p>
          </div>

          <div>
            <h1>Personally Identifying Information (PII)</h1>
            <p>
              No PII will be publicly available in the ADX-DW without the prior written consent of the individual. ADX
              Administrators will verify the identity of any persons reporting data into the ADX-DW. Individuals may
              decide at any time to remove their information from the ADX-DW database by contacting the ADX
              administrators at <strong><a href="mailto:hello@adxproject.org">hello@adxproject.org</a></strong>
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
<script>
export default {
  data() {
    return {
      path: "Data Policy"
    }
  },
  created() {
    this.$nuxt.$emit('breadcrumb', this.path);
  }
}
</script>
